package ap.raif;

public enum RaifFieldComposeType {

    ORIGIN_PRIMARY,
    VENGRO_PRIMARY,
    VENGRO_PRIMARY_CLASS,
    VENGRO_PRIMARY_CLASS_TO_STRING,
    ORIGIN_FULL,
    VENGRO_FUll,
    JNA_INT_VARIABLES_DECLARATION,
    JNA_STRING_VARIABLES_DECLARATION,
    JNA_BYTE_ARRAY_DECLARATION,
    JNA_DTOR_FILL_DECLARATION,
    JNA_GET_FIELD_ORDER,
    JNA_GETTERS_SETTERS,
    DEFAULT
}
